In [1]:
l = [1,2,3,4,5,6]


import numpy as np

a = np.array(l)
a

array([1, 2, 3, 4, 5, 6])

In [2]:
# Inserting single value in array    Syntax :- numpy.array(array_name,item to insert)

np.append(a,7)

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
np.append(a,[8])

array([1, 2, 3, 4, 5, 6, 8])

In [4]:
# Inserting Multiple values in array      # Syntax :- numpy.array(array_name,[items to insert])

np.append(a,[9,10,11])

array([ 1,  2,  3,  4,  5,  6,  9, 10, 11])

In [5]:
np.append(a,[[10,20,30]])         # It can not append the list of items in the 1D array 

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30])

In [6]:
# Replacing a value in array     Syntax :- array_name[index_number] = New_Assinging_value

a[0] = 100
a[3] = 400
a

array([100,   2,   3, 400,   5,   6])

In [7]:
# Replacing multiple values with one value    Syntax :- array_name[list of index_numbers] = New_Assinging_value

a[[0,3]] = 101
a[[2,4]] = 500
a

array([101,   2, 500, 101, 500,   6])

In [8]:
# Replacing multiple values with multiple values    Syntax :- array_name[list of index_numbers] = New_Assinging_values

a[[0,1]] = 10,20
a[[5,2,3]] = 100,200,300 
a

array([ 10,  20, 200, 300, 500, 100])

In [9]:
a[[2,3]] = 1,2,3     # No. of passing index and assinging values should be equal

ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,)

In [10]:
a[[0,2,5]] = 54,44,55,65

ValueError: shape mismatch: value array of shape (4,) could not be broadcast to indexing result of shape (3,)

In [13]:
l = [1,2,3,4,5,6]


import numpy as np

a = np.array(l)
a

array([1, 2, 3, 4, 5, 6])

In [15]:
# Deleting a value from array    Syntax :- np.delete(array_name,index_number of item want to remove)

np.delete(a,1)

array([1, 3, 4, 5, 6])

In [18]:
np.delete(a,4)

array([1, 2, 3, 4, 6])

In [19]:
# Deleting multiple values from array    Syntax :- np.delete(array_name,list of index_number of item want to remove)

np.delete(a,[0,2,5])


array([2, 4, 5])

In [20]:
np.delete(a,[0,4,2,3])

array([2, 6])